vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set number")
vim.cmd("set wrap")
vim.cmd("set linebreak")
vim.cmd("set showmatch")
vim.cmd("set autoindent")
vim.g.mapleader = " "
